version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend/
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    restart: always

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always
